default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "dynflow_orchestrator"
      threads: 1
      processes: 1
      polling_interval: 0.1
    - queues: "default"
      threads: 5
      processes: 3
      polling_interval: 0.1

development:
 <<: *default
#
# test:
#  <<: *default
#
# production:
#  <<: *default
